### ISSUE TITLE
Error implementación de PRINTN en C

### ISSUE THREAD

**Issue by swirzt** [compiladores-lcc/compiladores2021#3]
Al ejecutar el código en C, la operación PRINTN no imprime nada, se soluciona cambiando lo siguiente:
```c
printf("%" PRIu32 "\n", i);
```
por
```c
wprintf(L"%" PRIu32 "\n", i);
```

Creo que ocurre porque C no mezcla las salidas de char y wchar, en la operación de PRINT se usa wchar.

**Comment by mjaskelioff** [comment]
Corregido!
